# Generated by Django 4.1.1 on 2022-09-27 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vendor', '0001_initial'),
        ('Inventory', '0003_delete_purchaseorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('po_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.FloatField(default=200000)),
                ('datettime', models.DateField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchesorder_purdetails_rel', to='Inventory.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_purchesorder_rel', to='Vendor.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderDetails',
            fields=[
                ('v_invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('purchaseorder', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchesorder_details_rel', to='Report.purchaseorder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_purdetails_rel', to='Vendor.vendor')),
            ],
        ),
    ]
