# Generated by Django 4.1.1 on 2022-09-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0002_alter_purchaseorder_datettime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='datettime',
            field=models.DateField(auto_now=True),
        ),
    ]
