# Generated by Django 4.1.1 on 2022-09-28 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0003_alter_purchaseorder_datettime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='datettime',
            new_name='date',
        ),
    ]
