# Generated by Django 4.1.1 on 2022-09-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0004_rename_datettime_purchaseorder_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateField(),
        ),
    ]
