# Generated by Django 4.1.1 on 2022-09-25 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vendor', '0001_initial'),
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_am',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gst',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_gst_rel', to='Inventory.category', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_product_rel', to='Inventory.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_product_rel', to='Inventory.discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_product_rel', to='Inventory.gst'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_product_rel', to='Vendor.vendor'),
        ),
    ]
