# Generated by Django 4.1.1 on 2022-09-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_product_total_am_alter_gst_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_price',
            field=models.IntegerField(),
        ),
    ]
