# Generated by Django 4.1.1 on 2022-09-25 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_alter_product_p_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_am',
        ),
    ]
