# Generated by Django 4.1.1 on 2022-09-28 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_delete_purchaseorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='p_img',
        ),
    ]
