# Generated by Django 4.1.1 on 2022-09-28 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_remove_product_p_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='datetime',
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 9, 28, 4, 50, 14, 10374, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
