# Generated by Django 4.1.1 on 2022-09-26 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_excelfileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gst',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_gst_rel', to='Inventory.category'),
        ),
    ]
